services:
  aosp_openresty:
    container_name: aosp_openresty
    image: openresty/openresty:alpine
    ports:
      - 8080:80
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./html:/usr/local/openresty/nginx/html
    restart: unless-stopped
    networks:
      vpn:
        ipv4_address: 172.16.22.99

  aosp_opengrok:
    container_name: aosp_opengrok
    image: opengrok/docker:latest
    command: /usr/local/tomcat/bin/catalina.sh run
    volumes:
      - '/data/aospapp/src:/opengrok/src:ro'
      - '/data/aospapp/data:/opengrok/data'
      - '/data/aospapp/etc_one:/opengrok/etc'
      - '/data/aospapp/webapps_one:/usr/local/tomcat/webapps'
    restart: unless-stopped
    networks:
      vpn:
        ipv4_address: 172.16.22.100

networks:
  vpn:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet:  172.16.22.0/24
          gateway: 172.16.22.1
